config/routes.rb
Rails.application.routes.draw do
  resources :user_roles
  resources :branch_users
  resources :parcel_routes
  get 'dashboard/index'
  resources :consignments
  devise_for :users
  
  get 'consignments/:id/approve' => 'consignments#approve', as: :approve_consignment
  get 'public/track' => 'public#track', as: :pub_track_consignment
  get 'track/track' => 'track#track', as: :track_consignment
  get 'track/history' => 'track#history', as: :track_showhistory
  get 'public/trackshow' => 'public#trackshow', as: :trackshow_consignment
  root to:  'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_user.rb
class BranchUser < ApplicationRecord
end

app/models/consignment.rb
class Consignment < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/parcel_route.rb
class ParcelRoute < ApplicationRecord
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name , :last_name])
  end
end

app/controllers/branch_users_controller.rb
class BranchUsersController < ApplicationController
  before_action :set_branch_user, only: [:show, :edit, :update, :destroy]

  # GET /branch_users
  # GET /branch_users.json
  def index
    @branch_users = BranchUser.all
  end

  # GET /branch_users/1
  # GET /branch_users/1.json
  def show
  end

  # GET /branch_users/new
  def new
    @branch_user = BranchUser.new
    @users = User.all.map { |p| p.email }
    @servicelocations = ParcelRoute.all.map { |p| p.city_1 }
    @servicelocations = @servicelocations.uniq
  end

  # GET /branch_users/1/edit
  def edit
  end

  # POST /branch_users
  # POST /branch_users.json
  def create
    @branch_user = BranchUser.new(branch_user_params)

    respond_to do |format|
      if @branch_user.save
        format.html { redirect_to @branch_user, notice: 'Branch user was successfully created.' }
        format.json { render :show, status: :created, location: @branch_user }
      else
        format.html { render :new }
        format.json { render json: @branch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branch_users/1
  # PATCH/PUT /branch_users/1.json
  def update
    respond_to do |format|
      if @branch_user.update(branch_user_params)
        format.html { redirect_to @branch_user, notice: 'Branch user was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch_user }
      else
        format.html { render :edit }
        format.json { render json: @branch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branch_users/1
  # DELETE /branch_users/1.json
  def destroy
    @branch_user.destroy
    respond_to do |format|
      format.html { redirect_to branch_users_url, notice: 'Branch user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch_user
      @branch_user = BranchUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_user_params
      params.require(:branch_user).permit(:email, :city)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index  
    @consignments = Consignment.all
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
end

app/controllers/track_controller.rb
class TrackController < ApplicationController
    def track
        
    end
    def history
    #@History1 = History.all
    @tid=params[:trackid]
    #@History = History.all(:conditions => ["trackid = ?", tid])
    @History1 = History.where(trackid: params[:trackid] )
    @History1.each do |history|
      puts history.event 
        
    end  
    puts @History1
    puts "Tracking clicked"
    puts params[:trackid]
    if params[:trackid]==nil
      puts "Empty Parameter"
    else
      puts "Non Empty Parameter"
    end 
    end
    
    
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :set_user_role, only: [:show, :edit, :update, :destroy]

  # GET /user_roles
  # GET /user_roles.json
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1
  # GET /user_roles/1.json
  def show
  end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
    @users = User.all.map { |p| p.email }

  end

  # GET /user_roles/1/edit
  def edit
  end

  # POST /user_roles
  # POST /user_roles.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to @user_role, notice: 'User role was successfully created.' }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_roles/1
  # PATCH/PUT /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to @user_role, notice: 'User role was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1
  # DELETE /user_roles/1.json
  def destroy
    @user_role.destroy
    respond_to do |format|
      format.html { redirect_to user_roles_url, notice: 'User role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_role_params
      params.require(:user_role).permit(:email, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branch_users_helper.rb
module BranchUsersHelper
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/parcel_routes_helper.rb
module ParcelRoutesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/dashboard/_clist.html.erb
<p id="notice" > <%= notice  %></p>
<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>id</th>
      <th>Destination pin</th>
      <th>Source pin</th>
      <th>Weight</th>
      <th>Tracking</th>
      <th>Source contact</th>
      <th>Destination contact</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @consignments.each do |consignment| %>
      <tr>
        <td><%= consignment.id %></td>
        <td><%= consignment.destination_pin %></td>
        <td><%= consignment.source_pin %></td>
        <td><%= consignment.weight %></td>
        <td><%= consignment.tracking_id %></td>
        <td><%= consignment.source_contact %></td>
        <td><%= consignment.destination_contact %></td>
        <td>
        <% case consignment.status 
         when  1 %>   
            Schedule Pending
         <%= link_to 'Schedule Pickup', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %>
         <% when 2%>
          Waiting for pickup
         <%= link_to 'Confirm Pickup', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %>
         <% when 3%>
         In Transit
         <%= link_to 'Confirm Arrival', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %>
        <% end %>
        </td>
        <td><%= link_to 'Edit', edit_consignment_path(consignment), class: "btn btn-secondary btn-sm"  %></td>
        <td><%= link_to 'Destroy', consignment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/dashboard/_dashuppermenu.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1 class="h2">Dashboard</h1>
<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group me-2">
    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
  </div>
  <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
    This week
  </button>
</div>
</div>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<%= link_to 'New Consignment', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'Consignment List', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'Consignment Management', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'User Management', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'Pickup Schedules', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'Delivery Schedules', new_consignment_path, class: "btn btn-success" %>
<%= link_to 'Tracking', track_consignment_path, class: "btn btn-success" %>
</div>

app/views/dashboard/index.html.erb
<h2>Consignment List</h2>
<%= render "clist" %>

app/views/track/history.html.erb
<h> <% @tid %> </h>
<table>
<tbody>
<% @History1.each do |history| %>
  <tr>
    <td><%= history.event %></td>
    <td><%= history.created_at %></td>
   </tr>
<% end %>   
<% puts @History1 %>
</tbody>
</table>

app/views/track/track.html.erb
<section class="form-auth text-center">
  <%= form_with url: track_showhistory_path, method: :get do |form| %>
    <h1 class="h3 mb-3 fw-normal">Tracking Id </h1>
   <%= form.text_field :trackid, autofocus: true, class: "form-control", placeholder: "Tracking ID", autocomplete: "off"  %>
    <%= form.submit "Search", class: "w-100 btn btn-lg btn-primary" %>
  <% end %>
</section>