config/routes.rb
Rails.application.routes.draw do
  resources :user_roles
  resources :branch_users
  resources :parcel_routes
  get 'dashboard/index'
  resources :consignments
  devise_for :users
  
  get 'consignments/:id/approve' => 'consignments#approve', as: :approve_consignment
  get 'public/track' => 'public#track', as: :pub_track_consignment
  get 'track/track' => 'track#track', as: :track_consignment
  get 'track/history' => 'track#history', as: :track_showhistory
  get 'public/trackshow' => 'public#trackshow', as: :trackshow_consignment
  root to:  'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_user.rb
class BranchUser < ApplicationRecord
end

app/models/consignment.rb
class Consignment < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/parcel_route.rb
class ParcelRoute < ApplicationRecord
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index  
    @consignments = Consignment.all
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
end

app/controllers/track_controller.rb
class TrackController < ApplicationController
    def track
        
    end
    def history
    #@History1 = History.all
    @tid=params[:trackid]
    #@History = History.all(:conditions => ["trackid = ?", tid])
    @History1 = History.where(trackid: params[:trackid] )
    @History1.each do |history|
      puts history.event 
        
    end  
    puts @History1
    puts "Tracking clicked"
    puts params[:trackid]
    if params[:trackid]==nil
      puts "Empty Parameter"
    else
      puts "Non Empty Parameter"
    end 
    end
    
    
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :set_user_role, only: [:show, :edit, :update, :destroy]

  # GET /user_roles
  # GET /user_roles.json
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1
  # GET /user_roles/1.json
  def show
  end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
    @users = User.all.map { |p| p.email }

  end

  # GET /user_roles/1/edit
  def edit
  end

  # POST /user_roles
  # POST /user_roles.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to @user_role, notice: 'User role was successfully created.' }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_roles/1
  # PATCH/PUT /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to @user_role, notice: 'User role was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1
  # DELETE /user_roles/1.json
  def destroy
    @user_role.destroy
    respond_to do |format|
      format.html { redirect_to user_roles_url, notice: 'User role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_role_params
      params.require(:user_role).permit(:email, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branch_users_helper.rb
module BranchUsersHelper
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/parcel_routes_helper.rb
module ParcelRoutesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParcelTrackingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

  <body>

    <% if !user_signed_in? %>
    <header>
    <%= render "layouts/nav/public" %>
     <%= yield %>
    </header>
  <% else %>
    <%= render "layouts/nav/dashboard" %>
    <div class="container-fluid">
      <div class="row">
      <%= render "layouts/nav/dashuppermenu" %>
          <%= yield %>
      </div>
    </div>
  <% end %>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">ParcelTrack</a>
         <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">
         <%= current_user.email + " : " +  current_user.user_roles %>
         </a>
        
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
             <%= current_user.user_roles %>
          </li>
          <li class="nav-item text-nowrap">
             <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
    </nav>

app/views/layouts/nav/_dashuppermenu.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1 class="h2">Parcel Tracking System</h1>

</div>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<% if current_user.user_roles != "Guest" %>
<%= link_to 'Dashboard', dashboard_index_path, class: "btn btn-success" %>
<%= link_to 'Route Management', parcel_routes_path, class: "btn btn-success" %>
<%= link_to 'User Management', user_roles_path, class: "btn btn-success" %>
<% end %>
<%= link_to 'Consignment List', consignments_path, class: "btn btn-success" %>
<%= link_to 'New Consignment', new_consignment_path, class: "btn btn-success" %>
</div>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home" , root_path, class: "nav-link active" %>
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
           <%= link_to "Dashboard",  dashboard_index_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
           <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Sign In",  new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Sign Up",  new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Book a Service",  new_consignment_path , class: "nav-link"  %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Track Consignment",  track_consignment_path, class: "nav-link" %>
        </li>
        </form>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
  
          <li class="nav-item">
             <%= link_to   consignments_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Consignements
            <% end %>
          </li>
          <li class="nav-item">
           <%= link_to   new_consignment_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              New
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to   parcel_routes_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Routes
             <% end %>
          </li>
            <li class="nav-item">
            <%= link_to   branch_users_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Branch Users
             <% end %>
          </li>
          <li class="nav-item">
             <%= link_to   track_consignment_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Tracking
            <% end %>
          </li>
        </ul>
      </div>
    </nav>