config/routes.rb
Rails.application.routes.draw do
  resources :user_roles
  resources :branch_users
  resources :parcel_routes
  get 'dashboard/index'
  resources :consignments
  devise_for :users
  
  get 'consignments/:id/approve' => 'consignments#approve', as: :approve_consignment
  get 'public/track' => 'public#track', as: :pub_track_consignment
  get 'track/track' => 'track#track', as: :track_consignment
  get 'track/history' => 'track#history', as: :track_showhistory
  get 'public/trackshow' => 'public#trackshow', as: :trackshow_consignment
  root to:  'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/branch_user.rb
class BranchUser < ApplicationRecord
end

app/controllers/branch_users_controller.rb
class BranchUsersController < ApplicationController
  before_action :set_branch_user, only: [:show, :edit, :update, :destroy]

  # GET /branch_users
  # GET /branch_users.json
  def index
    @branch_users = BranchUser.all
  end

  # GET /branch_users/1
  # GET /branch_users/1.json
  def show
  end

  # GET /branch_users/new
  def new
    @branch_user = BranchUser.new
    @users = User.all.map { |p| p.email }
    @servicelocations = ParcelRoute.all.map { |p| p.city_1 }
    @servicelocations = @servicelocations.uniq
  end

  # GET /branch_users/1/edit
  def edit
  end

  # POST /branch_users
  # POST /branch_users.json
  def create
    @branch_user = BranchUser.new(branch_user_params)

    respond_to do |format|
      if @branch_user.save
        format.html { redirect_to @branch_user, notice: 'Branch user was successfully created.' }
        format.json { render :show, status: :created, location: @branch_user }
      else
        format.html { render :new }
        format.json { render json: @branch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branch_users/1
  # PATCH/PUT /branch_users/1.json
  def update
    respond_to do |format|
      if @branch_user.update(branch_user_params)
        format.html { redirect_to @branch_user, notice: 'Branch user was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch_user }
      else
        format.html { render :edit }
        format.json { render json: @branch_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branch_users/1
  # DELETE /branch_users/1.json
  def destroy
    @branch_user.destroy
    respond_to do |format|
      format.html { redirect_to branch_users_url, notice: 'Branch user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch_user
      @branch_user = BranchUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_user_params
      params.require(:branch_user).permit(:email, :city)
    end
end

app/helpers/branch_users_helper.rb
module BranchUsersHelper
end

app/views/branch_users/_form.html.erb
<%= bootstrap_form_with(model: branch_user, local: true) do |form| %>
  <% if branch_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch_user.errors.count, "error") %> prohibited this branch_user from being saved:</h2>

      <ul>
        <% branch_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.select(:email, options_for_select(@users  ), prompt: "Please Select" ) %>

   <%= form.select(:city, options_for_select(@servicelocations  ), prompt: "Please Select" ) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/branch_users/edit.html.erb
<h1>Editing Branch User</h1>

<%= render 'form', branch_user: @branch_user %>

<%= link_to 'Show', @branch_user %> |
<%= link_to 'Back', branch_users_path %>

app/views/branch_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Branch Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branch_users.each do |branch_user| %>
      <tr>
        <td><%= branch_user.email %></td>
        <td><%= branch_user.city %></td>
        <td><%= link_to 'Show', branch_user %></td>
        <td><%= link_to 'Edit', edit_branch_user_path(branch_user) %></td>
        <td><%= link_to 'Destroy', branch_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch User', new_branch_user_path %>

app/views/branch_users/new.html.erb
<h1>New Branch User</h1>

<%= render 'form', branch_user: @branch_user %>

<%= link_to 'Back', branch_users_path %>

app/views/branch_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @branch_user.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @branch_user.city %>
</p>

<%= link_to 'Edit', edit_branch_user_path(@branch_user) %> |
<%= link_to 'Back', branch_users_path %>