config/routes.rb
Rails.application.routes.draw do
  resources :user_roles
  resources :branch_users
  resources :parcel_routes
  get 'dashboard/index'
  resources :consignments
  devise_for :users
  
  get 'consignments/:id/approve' => 'consignments#approve', as: :approve_consignment
  get 'public/track' => 'public#track', as: :pub_track_consignment
  get 'track/track' => 'track#track', as: :track_consignment
  get 'track/history' => 'track#history', as: :track_showhistory
  get 'public/trackshow' => 'public#trackshow', as: :trackshow_consignment
  root to:  'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/consignment.rb
class Consignment < ApplicationRecord
end

app/controllers/consignments_controller.rb
class ConsignmentsController < ApplicationController
  before_action :set_consignment, only: [:show, :edit, :update, :destroy]

  # GET /consignments
  # GET /consignments.json
  def index
    @branchdetails = BranchUser.find_by(email: current_user.email)
    @userrole = UserRole.find_by(email: current_user.email)
    puts "1"
      if @userrole.role  == "Admin"
        @consignments = Consignment.all
      elsif(@userrole.role   == "Employee")
        puts "2"
        if @branchdetails != nil 
          query = "(status <= 4 and source_city=?) or ( status = 4 and current_city=?) or (status =5 and next_city=?) or ( status > 5 and destination_city=?)"
          @consignments = Consignment.where(query, @branchdetails.city,@branchdetails.city,@branchdetails.city ,@branchdetails.city )
          #@consignments = Consignment.where(source_city: @branchdetails.city)
        end
      else
        puts "3"
        puts current_user.email,@userrole.role 
        query = "(customer_email=?)"
        @consignments = Consignment.where(query, current_user.email )
        puts @consignments
      end
      
      if @consignments == nil 
        @consignments =[]
      end
     
  end

  # GET /consignments/1
  # GET /consignments/1.json
  def show
    
    #@History = History.all(:conditions => ["trackid = ?", @tid])
    #@History1 = History.where(trackid: params[:trackid] )
    @Cons=Consignment.find(params[:id])
    @tid=@Cons.tracking_id
    @History = History.where(trackid: @tid )
    puts "tid is :"
    puts @tid
    puts @History
  end

  # GET /consignments/new
  def new
    @servicelocations = ParcelRoute.all.map { |p| p.city_1 }
    @servicelocations = @servicelocations.uniq
    @consignment = Consignment.new

    #TwilioClient.new.send_text("+917200668804","Hello")
  end

  # GET /consignments/1/edit
  def edit
    @servicelocations = ParcelRoute.all.map { |p| p.city_1 }
    @servicelocations = @servicelocations.uniq
  end

  # POST /consignments
  # POST /consignments.json
  def create
        
    @consignment = Consignment.new(consignment_params)
    @consignment.status = 1
    @paths = RouteFind.new.findpath(@consignment.source_city, @consignment.destination_city )
    @consignment.estimated_time = @paths.last
    puts ".......Controller "  
    if user_signed_in?
      @consignment.customer_email = current_user.email
    end
    puts @paths
    respond_to do |format|
      if @consignment.save
        #puts "Consignment Paramets"
        #puts @consignment.id
        cid= @consignment.id.to_s
        #puts cid
        @consignment.tracking_id="IN-"+generate_code(5)+"-"+cid
        @consignment.save
        smob=@consignment.source_contact
        dmob=@consignment.destination_contact
        @History = History.new(:trackid =>@consignment.tracking_id,:event=>"Consignment Registered" )
        if @History.save
          msgtxt="Your consignment is booked with tracking id:"+@consignment.tracking_id
          TwilioClient.new.send_text(smob,msgtxt)
          msgtxt="A consignment is booked for you with tracking id:"+@consignment.tracking_id
          TwilioClient.new.send_text(dmob,msgtxt)
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end  
        format.html { redirect_to @consignment, notice: 'Consignment was successfully created.' }
        format.json { render :show, status: :created, location: @consignment }
        puts "This is a sample"
        puts @consignment.id
      else
        format.html { render :new }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end
  def approve
    @consignment = Consignment.find(params[:id])
    smob=@consignment.source_contact
    dmob=@consignment.destination_contact
    case @consignment.status
    when 1
      @consignment.status=2
      @buttontext="Schedule"
      @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Scheduled Pickup from Customer" )
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 

    when 2
      @consignment.status=3
      @buttontext="Pickup"
      @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Received from Customer" )
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 

    when 3
      @consignment.current_city = @consignment.source_city
      @consignment.status=4
      @buttontext="Received"
      
    when 4
      next_location = RouteFind.new.findpath( @consignment.current_city,@consignment.destination_city)
      @consignment.next_city = next_location[1]
      puts next_location
      puts ".......Status 4 ............."
      puts next_location[1]
      @consignment.status = 5
      @buttontext="Left"
      @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Left from Base Node at "+@consignment.current_location.to_s )
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 
    when 5
      if @consignment.next_city == @consignment.destination_city
        @consignment.current_city = @consignment.next_city
        @consignment.status=6
        @buttontext="Received"
        @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Received at Destination Node at "+@consignment.current_location.to_s )
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 
      else
        @consignment.current_city = @consignment.next_city
        @consignment.status=4
        @buttontext="Received"
        @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Received at Intermediate Node at "+@consignment.current_location.to_s )
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 
      end
    when 6
      @consignment.status=7
      @buttontext="Schedule Delivery"
      @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Out for Delivery")
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 
    when 7
      @consignment.status=8
      @buttontext="Deliver"
      puts "........."
      puts "@consignment.status "
      @History = History.new(:trackid =>@consignment.tracking_id,:user=> current_user.email ,:event=>"Parcel Delivered")
        if @History.save
          
        else
          format.html { render :new }
          format.json { render json: @History.errors, status: :unprocessable_entity }
        end 
    when 8
      puts "........."
      puts "@consignment.status "
      @buttontext="Show History"
    end
  end
  # PATCH/PUT /consignments/1
  # PATCH/PUT /consignments/1.json
  def update 
    puts "........"
    puts consignment_params
    respond_to do |format|
      if @consignment.update(consignment_params)
        #smob=@consignment.source_contact
        dmob=@consignment.destination_contact
        case @consignment.status
        when 2
          #msgtxt="Your consignment with tracking id:"+@consignment.tracking_id+" is approved for pickup on "+@consignment.pickup_schedulle
          #puts msgtxt
          #TwilioClient.new.send_text(smob,msgtxt)
          #msgtxt="A consignment is booked for you with tracking id:"+@consignment.tracking_id
          #TwilioClient.new.send_text(dmob,msgtxt)
        end
        format.html { redirect_to consignments_url, notice: 'Consignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @consignment }
       
      else
        format.html { render :edit }
        format.json { render json: @consignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consignments/1
  # DELETE /consignments/1.json
  def destroy
    @consignment.destroy
    respond_to do |format|
      format.html { redirect_to consignments_url, notice: 'Consignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consignment
      @consignment = Consignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consignment_params
      params.require(:consignment).permit(:user_id, :destination_pin, :source_pin, :status, :weight, :tracking_id, :source_contact, :destination_contact, :current_location, :next_location, :source_city, :destination_city, :current_city, :next_city)
    end
    def generate_code(number)
      charset = Array('A'..'Z') + Array('1'..'9')
      Array.new(number) { charset.sample }.join
    end
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
end

app/views/consignments/_form.html.erb
<%= bootstrap_form_with(model: consignment, local: true) do |form| %>
  <% if consignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consignment.errors.count, "error") %> prohibited this consignment from being saved:</h2>

      <ul>
        <% consignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= form.select(:source_city, options_for_select(@servicelocations  ), prompt: "Please Select" ) %>
      <%= form.select(:destination_city, options_for_select(@servicelocations  ), prompt: "Please Select") %>
    <%= form.text_field :weight, class: "form-control" %>
    <%= form.text_field :source_contact, class: "form-control"  %>
    <%= form.text_field :destination_contact, class: "form-control" %>
    <%= form.submit "Submit", class: "btn btn-primary" %>

<% end %>

app/views/consignments/approve.html.erb
<%= bootstrap_form_with(model: @consignment, local: true) do |form| %>
  <% if @consignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consignment.errors.count, "error") %> prohibited this consignment from being saved:</h2>

      <ul>
        <% @consignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :status, :value => @consignment.status%>
  </div>
  <% case @consignment.status 
         when  2 %>
        <div class="field">
        <%= form.number_field(:pickup_time) %>
        </div> 
        <% when 4 %>
          <div class="field">
          <%= form.text_field :current_city, :value => @consignment.current_city %>
        </div>
        <% when 5%>
        <div class="field">
          <%= form.text_field :current_city, :value => @consignment.current_city%>
        </div>
        <div class="field"> 
          <%= form.text_field :next_city, :value => @consignment.next_city %>
        </div>
        <% when 6 %>
        <div class="field">
        <%= form.number_field(:delivery_time) %>
        </div>
  <% end %>

  <div class="actions">
    <%= form.submit @buttontext %>
  </div>
<% end %>

app/views/consignments/edit.html.erb
<h1>Editing Consignment</h1>

<%= render 'form', consignment: @consignment %>

<%= link_to 'Show', @consignment %> |
<%= link_to 'Back', consignments_path %>

app/views/consignments/index.html.erb
<p id="notice" > <%= notice  %></p>
<h1>Consignments</h1>
<div class="table-responsive">
  <table class="table  table-primary table-striped table-sm" >
  <thead "table-dark">
    <tr>
      <th>id</th>
      <th>Destination pin</th>
      <th>Source pin</th>
      <th>Weight</th>
      <th>Tracking</th>
      <th>Source contact</th>
      <th>Destination contact</th>
      <th>Estimated Total time </th>
      <th>Status</th>
      <th colspan="3">Actions </th>
    </tr>
  </thead>

  <tbody>
    <% @consignments.each do |consignment| %>
      <tr>
        <td><%= consignment.id %></td>
        <td><%= consignment.source_city %></td>
        <td><%= consignment.destination_city %></td>
        <td><%= consignment.weight %></td>
        <td><%= consignment.tracking_id %></td>
        <td><%= consignment.source_contact %></td>
        <td><%= consignment.destination_contact %></td>
        <td><%= consignment.estimated_time %></td>
        <% if current_user.user_roles != "Guest" %>
            <% case consignment.status 
                  when  1 %>   
                  <td>Schedule Pending </td>
                  <td><%= link_to 'Schedule Pickup', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                  
                  <% when 2%>
                    <td>Waiting for pickup </td>
                    <td><%= link_to 'Confirm Pickup', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    
                    <% when  3 %>
                    <td>Picked up the Consignment</td>
                    <td><%= link_to 'Confirm Receipt', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    
                    <% when 4 %>
                    <% status= "Received the consignment #{consignment.current_city} " %>
                    <td> <%= status %> </td>
                    <td><%= link_to 'Confirm Movement', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    
                    <% when 5 %>
                    <% status= "consignement Left from #{consignment.current_city} " %>
                    <td> <%= status %> </td>
                    <td><%= link_to 'Confirm Receipt ', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    <% when 6%>
                    <% status= "Consignment at destination station #{consignment.destination_city} " %>
                    <td> <%= status %> </td>
                    <td><%= link_to 'Schedule Delivery ', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    <% when 7%>
                    <% status= "Out for delivery" %>
                    <td> <%= status %> </td>
                    <td><%= link_to 'Confirm Delivery ', approve_consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
                    <% when 8%>
                    <% status= "Delivered" %>
                    <td> <%= status %> </td>
                    <td><%= link_to 'Show History ', consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
            <% end %>
            <td><%= link_to 'Edit', edit_consignment_path(consignment), class: "btn btn-secondary btn-sm"  %></td>
            <td><%= link_to 'Destroy', consignment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            <%else%>
            <td><%= link_to 'Track', consignment_path(consignment), class: "btn btn-primary btn-sm" %></td>
            <% end %>
          </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/consignments/new.html.erb
  
        
            <h1>New Consignment</h1>

            <%= render 'form', consignment: @consignment %>
            <% if user_signed_in? %>
            <%= link_to 'Back', consignments_path %>
            <% end %>

app/views/consignments/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Destination pin:</strong>
  <%= @consignment.destination_pin %>
</p>

<p>
  <strong>Source pin:</strong>
  <%= @consignment.source_pin %>
</p>

<p>
  <strong>Status:</strong>
  <%= @consignment.status %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @consignment.weight %>
</p>

<p>
  <strong>Tracking:</strong>
  <%= @consignment.tracking_id %>
</p>

<p>
  <strong>Source contact:</strong>
  <%= @consignment.source_contact %>
</p>

<p>
  <strong>Destination contact:</strong>
  <%= @consignment.destination_contact %>
</p>

<strong> Tracking Status </strong>
<table border=1px>
<tbody>
<th > Sl</th>
  <th align="center"> Event Time</th>
  <th > Description</th>
<% i=0 %>
<% @History.each do |history| %>
  <% i= i+1 %>
  <tr>
    <td align="center"><%= i %></td>
    <td><%= history.created_at %></td>
    <td><%= history.event %></td>
   </tr>
<% end %>   
<% puts @History1 %>
</tbody>
</table>
<% if user_signed_in? %>
<%= link_to 'Back', consignments_path %>
<% end %>